module.exports = {
  JPEG_BASE64: "/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAP//////////////////////////////////////////////////////////////////////////////////////wgALCAABAAEBAREA/8QAFAABAAAAAAAAAAAAAAAAAAAAAA//xAAVAQEBAAAAAAAAAAAAAAAAAAAAAP/aAAgBAQAAPwBB/9k=",
  MP4_BASE64: "AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAAAIZnJlZQAABXltZGF0AAACrgYF//+//7H/wA1BwEGxgwFw/8EAEAAAO14A//L//+14A//L//8ABqIHYhAigAEKAAAABRAAAAAsAAB//0eAAAAAAv4gAAAAAAgAAAAAHgAAAAA2gAAAAAKwAAAAAXAAAAAAMHh//4uAAAAAAa/4AAAAAAEAAAAAB4AAAAAMoAAAAAC8AAAAAGwAAAAABBAAAAAFwAAAAAHgAAAAAXAAAAAAKAAAAAAs////zAAAAAAOAAA=="
};
